workflow:
  rules:
    - if: "$CI_COMMIT_BRANCH"

stages:
  - build
  - test

build_app:
  stage: build
  script:
    - sudo docker-compose build --no-cache
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

test_app:
  stage: test
  before_script:
    - sudo docker-compose up --detach
  script:
    - cd tests/APIgateway.Tests
    - dotnet test
  after_script:
    - sudo docker-compose down
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
