workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'
    
tests:
  stage: test
  script:
    - cd tests/monitor.Tests
    - dotnet test

deploying:
  stage: deploy
  script:
    - sudo docker-compose up --build
    - sleep 180
    - sudo docker-compose down
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
