workflow:
  rules:
    - if: "$CI_COMMIT_BRANCH"

stages:
  - lint
  - build
  - test
  - deploy

lint_APIgateway:
  stage: lint
  script:
    - cd APIgateway
    - dotnet clean
    - dotnet format --verify-no-changes
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

build_app:
  stage: build
  script:
    - sudo docker-compose build --no-cache
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

test_app:
  stage: test
  before_script:
    - sudo docker-compose up --detach
  script:
    - cd tests/APIgateway.Tests
    - dotnet test
  after_script:
    - sudo docker-compose down
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy_app:
  stage: deploy
  script:
    - sudo docker-compose up --detach
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
