workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

stages:
  - build
  - test

build_app:
  stage: build
  script:
    - sudo docker-compose up --build  --detach
    - sleep 10
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

test_app:
  stage: test
  script:
    - cd tests/monitor.Tests
    - dotnet test
  after_script:
    - sudo docker-compose down
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

