version: '3.8'

services:
  service1joonaspelttari:
    build:
      context: ./service1
    container_name: service1joonaspelttari
    networks:
      - app-network
    env_file:
      - .env.configs

  service2joonaspelttari:
    build:
      context: ./service2
    container_name: service2joonaspelttari
    networks:
      - app-network
    env_file:
      - .env.configs

  rabbitmqjoonaspelttari:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmqjoonaspelttari
    ports:
      - 15672:15672
    networks:
      - app-network

  monitorjoonaspelttari:
    build:
      context: ./monitor
    container_name: monitorjoonaspelttari
    ports:
      - 8087:8087
    networks:
      - app-network
    env_file:
      - .env.configs

networks:
  app-network:
    driver: bridge
