version: '3.8'

services:
  service1joonaspelttari:
    build:
      context: ./service1
    container_name: service1joonaspelttari
    networks:
      - app-network
    command: sh -c '/bin/wait-for-it.sh rabbitmqjoonaspelttari:5672 --timeout=100 -- node index.mjs'
    env_file:
      - .env.configs

  service2joonaspelttari:
    build:
      context: ./service2
    container_name: service2joonaspelttari
    networks:
      - app-network
    entrypoint:
      [
        "/wait-for-it.sh",
        "rabbitmqjoonaspelttari:5672",
        "-t",
        "100",
        "--",
        "dotnet",
        "service.dll"
      ]
    env_file:
      - .env.configs

  rabbitmqjoonaspelttari:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmqjoonaspelttari
    networks:
      - app-network

  monitorjoonaspelttari:
    build:
      context: ./monitor
    container_name: monitorjoonaspelttari
    ports:
      - 8087:8087
    networks:
      - app-network
    env_file:
      - .env.configs

networks:
  app-network:
    driver: bridge
