name: Linter

on: push

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run linter
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: exercise1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
